package com.medify.medifybackend.enums;

public enum Speciality {
    GYNAECOLOGY,
    GENERAL_PHYSICIAN,
    DERMATOLOGY,
    SEXOLOGY,
    PSYCHIATRY,
    PEDIATRICS,
    EAR_NOSE_THROAT,
    UROLOGY,
    ORTHOPEDIC,
    NEUROLOGY,
    CARDIOLOGY,
    DIET_AND_NUTRITION,
    OPHTHALMOLOGY,
    DENTISTRY,
    PULMONOLOGY,
    AYURVEDA,
    HOMEOPATHY,
    ONCOLOGY,
    PHYSIOTHERAPY,
    GENERAL_SURGERY,
    PSYCHOLOGY,
    NEPHROLOGY,
    RHEUMATOLOGY,
    GASTROENTEROLOGY,
    VETERINARY;
}
